user1  = User.create(email: "t@t.com", password: "123456" )
user2  = User.create(email: Faker::Internet.email, password: "123456")
user3  = User.create(email: Faker::Internet.email, password: "123456")
user4  = User.create(email: Faker::Internet.email, password: "123456")
user5  = User.create(email: Faker::Internet.email, password: "123456")
user6  = User.create(email: Faker::Internet.email, password: "123456")
user7  = User.create(email: Faker::Internet.email, password: "123456")
user8  = User.create(email: Faker::Internet.email, password: "123456")
user9  = User.create(email: Faker::Internet.email, password: "123456")
user10 = User.create(email: Faker::Internet.email, password: "123456")
user11 = User.create(email: Faker::Internet.email, password: "123456")
user12 = User.create(email: Faker::Internet.email, password: "123456")
user13 = User.create(email: Faker::Internet.email, password: "123456")
user14 = User.create(email: Faker::Internet.email, password: "123456")
user15 = User.create(email: Faker::Internet.email, password: "123456")
user16 = User.create(email: Faker::Internet.email, password: "123456")
user17 = User.create(email: Faker::Internet.email, password: "123456")
user18 = User.create(email: Faker::Internet.email, password: "123456")
user19 = User.create(email: Faker::Internet.email, password: "123456")
user20 = User.create(email: Faker::Internet.email, password: "123456")
user21 = User.create(email: Faker::Internet.email, password: "123456")
user22 = User.create(email: Faker::Internet.email, password: "123456")
user23 = User.create(email: Faker::Internet.email, password: "123456")
user24 = User.create(email: Faker::Internet.email, password: "123456")
user25 = User.create(email: Faker::Internet.email, password: "123456")
user26 = User.create(email: Faker::Internet.email, password: "123456")
user27 = User.create(email: Faker::Internet.email, password: "123456")
user28 = User.create(email: Faker::Internet.email, password: "123456")
user29 = User.create(email: Faker::Internet.email, password: "123456")
user30 = User.create(email: Faker::Internet.email, password: "123456")
user31 = User.create(email: Faker::Internet.email, password: "123456")
user32 = User.create(email: Faker::Internet.email, password: "123456")
user33 = User.create(email: Faker::Internet.email, password: "123456")
user34 = User.create(email: Faker::Internet.email, password: "123456")
user35 = User.create(email: Faker::Internet.email, password: "123456")
user36 = User.create(email: Faker::Internet.email, password: "123456")
user37 = User.create(email: Faker::Internet.email, password: "123456")

Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user2 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user3 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user4 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user5 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user6 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user7 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user8 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user9 )
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user10)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user11)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user12)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user13)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user14)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user15)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user16)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user17)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user18)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user19)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user20)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user21)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user22)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user23)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user24)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user25)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user26)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user27)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user28)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user29)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user30)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user31)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user32)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user33)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user34)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user35)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user36)
Profile.create(avatar: Faker::Avatar.image, name: Faker::Name.name, description: Faker::Lorem.sentences(1), user: user37)


allusers = User.all

allusers.each do |user|
  3.times do
    pust = Post.create(title: Faker::Hipster.sentences(1), image: Faker::Avatar.image, description: Faker::Hipster.sentences(1), user: user)
    Comment.create(comment: Faker::Hipster.sentences(1), user: allusers.sample, post: pust)
  end
end
